# Generated by Django 5.0.7 on 2026-04-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_OWNER', 'Super Owner'), ('OWNER', 'Owner'), ('COMPILER', 'Укладач'), ('USER', 'Користувач')], default='USER', max_length=20),
        ),
    ]
