# Generated by Django 5.0.7 on 2026-04-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Супер Адмін'), ('ADMIN', 'Адмін'), ('COMPILER', 'Укладач'), ('USER', 'Користувач')], default='USER', max_length=20),
        ),
    ]
