# Generated by Django 5.0.7 on 2026-03-05 20:06

import django.contrib.postgres.fields
import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('G', 'Загальний'), ('E', 'Навчальний'), ('S', 'Спеціалізований')], default='G', max_length=50)),
                ('language', models.CharField(choices=[('UK', 'Українська')], default='UK', max_length=32)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('corpus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.corpus')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilteredSubcorpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.corpus')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('texts', models.ManyToManyField(blank=True, to='corpus.text')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubcorpus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.corpus')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='user_subcorpus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.usersubcorpus'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='corpus.style')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'style')},
            },
        ),
        migrations.CreateModel(
            name='TextMetadata',
            fields=[
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='metadata', serialize=False, to='corpus.text')),
                ('year_of_creation', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('years_of_publication', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('authors_gender', models.CharField(blank=True, choices=[('M', 'Чоловіча'), ('F', 'Жіноча'), ('O', 'Інше'), ('U', 'Невідомо')], max_length=1, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True)),
                ('text_origin', models.CharField(blank=True, choices=[('O', 'Оригінал'), ('T', 'Переклад'), ('U', 'Невідомо')], max_length=1, null=True)),
                ('genres', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='style', chained_model_field='style', horizontal=True, to='corpus.genre')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='corpus.style')),
            ],
        ),
        migrations.AddConstraint(
            model_name='filteredsubcorpus',
            constraint=models.UniqueConstraint(fields=('name', 'corpus', 'creator'), name='unique_filtered_subcorpus_name'),
        ),
        migrations.AddConstraint(
            model_name='usersubcorpus',
            constraint=models.UniqueConstraint(fields=('creator', 'corpus'), name='unique_user_subcorpus_name'),
        ),
        migrations.AddConstraint(
            model_name='text',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('corpus__isnull', False), ('user_subcorpus__isnull', True)), models.Q(('corpus__isnull', True), ('user_subcorpus__isnull', False)), _connector='OR'), name='text_belongs_to_exactly_one_parent'),
        ),
    ]
