# Generated by Django 5.0.7 on 2026-04-10 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_corpuses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CorpusUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('V', 'Користувач-спростерігач'), ('E', 'Користувач-укладач')], default='V', max_length=30)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpus.corpus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'corpus')},
            },
        ),
        migrations.AddField(
            model_name='corpus',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='invited_corpuses', through='corpus.CorpusUserAccess', to=settings.AUTH_USER_MODEL),
        ),
    ]
