# Generated by Django 5.0.7 on 2026-04-10 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_alter_corpus_creator_corpususeraccess_corpus_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpususeraccess',
            name='access_level',
            field=models.CharField(choices=[('V', 'Перегляд'), ('E', 'Редагування')], default='V', max_length=30),
        ),
    ]
