# Generated by Django 5.0.7 on 2026-04-29 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_alter_corpususeraccess_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.corpus'),
        ),
        migrations.AlterField(
            model_name='text',
            name='user_subcorpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corpus.usersubcorpus'),
        ),
    ]
