# Generated by Django 5.0.7 on 2026-08-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_alter_text_corpus_alter_text_user_subcorpus'),
    ]

    operations = [
        migrations.AddField(
            model_name='filteredsubcorpus',
            name='filters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filteredsubcorpus',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
