# Generated by Django 5.0.7 on 2026-07-23 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0004_alter_text_corpus_alter_text_user_subcorpus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcorpusAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('VIEW', 'Перегляд'), ('EDIT', 'Редагування')], default='VIEW', max_length=4)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubcorpusShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(editable=False, max_length=8, unique=True)),
                ('link_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('permission_level', models.CharField(choices=[('VIEW', 'Перегляд'), ('EDIT', 'Редагування')], default='VIEW', max_length=4)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('use_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='usersubcorpus',
            name='unique_user_subcorpus_name',
        ),
        migrations.AddField(
            model_name='usersubcorpus',
            name='parent_subcorpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='derived_subcorpora', to='corpus.usersubcorpus'),
        ),
        migrations.AddConstraint(
            model_name='usersubcorpus',
            constraint=models.UniqueConstraint(fields=('name', 'creator', 'corpus'), name='unique_user_subcorpus_name'),
        ),
        migrations.AddField(
            model_name='subcorpusaccessgrant',
            name='subcorpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='corpus.usersubcorpus'),
        ),
        migrations.AddField(
            model_name='subcorpusaccessgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcorpus_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcorpusshare',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subcorpusshare',
            name='subcorpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='corpus.usersubcorpus'),
        ),
        migrations.AddField(
            model_name='subcorpusaccessgrant',
            name='share',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grants', to='corpus.subcorpusshare'),
        ),
        migrations.AlterUniqueTogether(
            name='subcorpusaccessgrant',
            unique_together={('subcorpus', 'user')},
        ),
    ]
