# Generated by Django 5.0.7 on 2026-08-03 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_filteredsubcorpus_filters_and_more'),
        ('corpus', '0006_corpusshare'),
    ]

    operations = [
    ]
